In [64]:
import pandas as pd
import numpy as np

## Data Frames

In [65]:
users = {
    "ID": [1,2,3,4,5],
    "Username": ["Victor", "Alex", "Tanya", "Lev", "Timofey"],
    "Age": [18, 35, 25, 38, 45],
    "Date": pd.to_datetime(["2032-01-01", "2032-02-15","2032-04-25","2032-06-21","2032-09-15"]),
    "Posts": [150, 230, 80, 420, None],
    "Reputation": [500, 720, 200, 940, 500]
}
df = pd.DataFrame(users)
df

   ID Username  Age       Date  Posts  Reputation
0   1   Victor   18 2032-01-01  150.0         500
1   2     Alex   35 2032-02-15  230.0         720
2   3    Tanya   25 2032-04-25   80.0         200
3   4      Lev   38 2032-06-21  420.0         940
4   5  Timofey   45 2032-09-15    NaN         500

In [66]:
df.shape

(5, 6)

In [67]:
# Column labels
df.columns.tolist()

['ID', 'Username', 'Age', 'Date', 'Posts', 'Reputation']

In [68]:
# Row labels
df.index.tolist()

[0, 1, 2, 3, 4]

In [69]:
df.values

array([[1, 'Victor', 18, Timestamp('2032-01-01 00:00:00'), 150.0, 500],
       [2, 'Alex', 35, Timestamp('2032-02-15 00:00:00'), 230.0, 720],
       [3, 'Tanya', 25, Timestamp('2032-04-25 00:00:00'), 80.0, 200],
       [4, 'Lev', 38, Timestamp('2032-06-21 00:00:00'), 420.0, 940],
       [5, 'Timofey', 45, Timestamp('2032-09-15 00:00:00'), nan, 500]],
      dtype=object)

In [70]:
df.values[1,1]

'Alex'

In [71]:
# First 3 rows
df.head(3)

   ID Username  Age       Date  Posts  Reputation
0   1   Victor   18 2032-01-01  150.0         500
1   2     Alex   35 2032-02-15  230.0         720
2   3    Tanya   25 2032-04-25   80.0         200

In [72]:
# Last 2 rows
df.tail(2)

   ID Username  Age       Date  Posts  Reputation
3   4      Lev   38 2032-06-21  420.0         940
4   5  Timofey   45 2032-09-15    NaN         500

In [73]:
df.describe().round(2)

         ID    Age                 Date   Posts  Reputation
count  5.00   5.00                    5    4.00        5.00
mean   3.00  32.20  2032-04-28 00:00:00  220.00      572.00
min    1.00  18.00  2032-01-01 00:00:00   80.00      200.00
25%    2.00  25.00  2032-02-15 00:00:00  132.50      500.00
50%    3.00  35.00  2032-04-25 00:00:00  190.00      500.00
75%    4.00  38.00  2032-06-21 00:00:00  277.50      720.00
max    5.00  45.00  2032-09-15 00:00:00  420.00      940.00
std    1.58  10.71                  NaN  146.74      276.62

In [74]:
# D = EX² - E²X
age = df["Age"]
squared_avg = age.mean()**2
avg_of_squares = age.apply(lambda x: x**2).sum() / len(age)
var = avg_of_squares - squared_avg
std = var ** 0.5
std

9.579144011862425

In [75]:
# D = E(X - EX)²
age = df["Age"]
avg = age.mean()
var = age.apply(lambda x: (x - avg)**2).sum() / len(age)
std = var ** 0.5
std

9.579144011862438

In [76]:
df["Age"].std(ddof=0)

9.579144011862438

In [77]:
df

   ID Username  Age       Date  Posts  Reputation
0   1   Victor   18 2032-01-01  150.0         500
1   2     Alex   35 2032-02-15  230.0         720
2   3    Tanya   25 2032-04-25   80.0         200
3   4      Lev   38 2032-06-21  420.0         940
4   5  Timofey   45 2032-09-15    NaN         500

In [78]:
# Create new dataframe with selected column types
df.select_dtypes(include="int")

   ID  Age  Reputation
0   1   18         500
1   2   35         720
2   3   25         200
3   4   38         940
4   5   45         500

In [79]:
# Create new dataframe without selected column types
df.select_dtypes(exclude="int")

  Username       Date  Posts
0   Victor 2032-01-01  150.0
1     Alex 2032-02-15  230.0
2    Tanya 2032-04-25   80.0
3      Lev 2032-06-21  420.0
4  Timofey 2032-09-15    NaN

In [80]:
df.isna()

      ID  Username    Age   Date  Posts  Reputation
0  False     False  False  False  False       False
1  False     False  False  False  False       False
2  False     False  False  False  False       False
3  False     False  False  False  False       False
4  False     False  False  False   True       False

In [81]:
df.isna().sum()

ID            0
Username      0
Age           0
Date          0
Posts         1
Reputation    0
dtype: int64

## Series

In [82]:
series = df["Username"]
series

0     Victor
1       Alex
2      Tanya
3        Lev
4    Timofey
Name: Username, dtype: object

In [83]:
series.values

array(['Victor', 'Alex', 'Tanya', 'Lev', 'Timofey'], dtype=object)

In [85]:
df["Reputation"].value_counts()

Reputation
500    2
720    1
200    1
940    1
Name: count, dtype: int64

In [86]:
df["Reputation"].unique()

array([500, 720, 200, 940], dtype=int64)

In [87]:
df["Username"].sort_values()

1       Alex
3        Lev
2      Tanya
4    Timofey
0     Victor
Name: Username, dtype: object