In [27]:
import pandas as pd
import numpy as np

In [28]:
users = {
    "ID": [1,2,3,4,5],
    "Username": ["Victor", "Alex", "Tanya", "Lev", "Timofey"],
    "Age": [18, 35, 25, 38, 45],
    "Date": pd.to_datetime(["2032-01-01", "2032-02-15","2032-04-25","2032-06-21","2032-09-15"]),
    "Posts": [150, 230, 80, 420, None],
    "Reputation": [500, 720, 200, 940, 500]
}
df = pd.DataFrame(users)
df

   ID Username  Age       Date  Posts  Reputation
0   1   Victor   18 2032-01-01  150.0         500
1   2     Alex   35 2032-02-15  230.0         720
2   3    Tanya   25 2032-04-25   80.0         200
3   4      Lev   38 2032-06-21  420.0         940
4   5  Timofey   45 2032-09-15    NaN         500

## Filtering

In [29]:
df[["Username", "Age"]]

  Username  Age
0   Victor   18
1     Alex   35
2    Tanya   25
3      Lev   38
4  Timofey   45

In [30]:
df.loc[3]

ID                              4
Username                      Lev
Age                            38
Date          2032-06-21 00:00:00
Posts                       420.0
Reputation                    940
Name: 3, dtype: object

In [31]:
df.loc[2:3]

   ID Username  Age       Date  Posts  Reputation
2   3    Tanya   25 2032-04-25   80.0         200
3   4      Lev   38 2032-06-21  420.0         940

In [32]:
df.loc[2:3, ["Username", "Reputation"]]

  Username  Reputation
2    Tanya         200
3      Lev         940

In [33]:
df.iloc[2:4, 1:4]

  Username  Age       Date
2    Tanya   25 2032-04-25
3      Lev   38 2032-06-21

In [34]:
# Select all rows
df.iloc[:, 1:4]

  Username  Age       Date
0   Victor   18 2032-01-01
1     Alex   35 2032-02-15
2    Tanya   25 2032-04-25
3      Lev   38 2032-06-21
4  Timofey   45 2032-09-15

In [35]:
# All rows where Age >= 25
df[df["Age"] > 25]

   ID Username  Age       Date  Posts  Reputation
1   2     Alex   35 2032-02-15  230.0         720
3   4      Lev   38 2032-06-21  420.0         940
4   5  Timofey   45 2032-09-15    NaN         500

In [36]:
df[(df["Age"] > 25) & (df["Posts"] > 300)]

   ID Username  Age       Date  Posts  Reputation
3   4      Lev   38 2032-06-21  420.0         940

In [37]:
df["Reputation"].isin([200, 500])

0     True
1    False
2     True
3    False
4     True
Name: Reputation, dtype: bool

In [38]:
df[df["Reputation"].isin([200, 500])]

   ID Username  Age       Date  Posts  Reputation
0   1   Victor   18 2032-01-01  150.0         500
2   3    Tanya   25 2032-04-25   80.0         200
4   5  Timofey   45 2032-09-15    NaN         500

In [39]:
df[df["Posts"].isin(range(200, 500))]

   ID Username  Age       Date  Posts  Reputation
1   2     Alex   35 2032-02-15  230.0         720
3   4      Lev   38 2032-06-21  420.0         940

In [40]:
date_range = pd.date_range(start="2032-03-01", end="2032-08-01")
date_range

DatetimeIndex(['2032-03-01', '2032-03-02', '2032-03-03', '2032-03-04',
               '2032-03-05', '2032-03-06', '2032-03-07', '2032-03-08',
               '2032-03-09', '2032-03-10',
               ...
               '2032-07-23', '2032-07-24', '2032-07-25', '2032-07-26',
               '2032-07-27', '2032-07-28', '2032-07-29', '2032-07-30',
               '2032-07-31', '2032-08-01'],
              dtype='datetime64[ns]', length=154, freq='D')

In [41]:
date_range = pd.date_range(start="2032-03-01", end="2032-08-01")
df[df["Date"].isin(date_range)]

   ID Username  Age       Date  Posts  Reputation
2   3    Tanya   25 2032-04-25   80.0         200
3   4      Lev   38 2032-06-21  420.0         940

## Sorting

In [42]:
df.sort_values(by="Age")

   ID Username  Age       Date  Posts  Reputation
0   1   Victor   18 2032-01-01  150.0         500
2   3    Tanya   25 2032-04-25   80.0         200
1   2     Alex   35 2032-02-15  230.0         720
3   4      Lev   38 2032-06-21  420.0         940
4   5  Timofey   45 2032-09-15    NaN         500

In [43]:
df.sort_values(by="Date", ascending=False)

   ID Username  Age       Date  Posts  Reputation
4   5  Timofey   45 2032-09-15    NaN         500
3   4      Lev   38 2032-06-21  420.0         940
2   3    Tanya   25 2032-04-25   80.0         200
1   2     Alex   35 2032-02-15  230.0         720
0   1   Victor   18 2032-01-01  150.0         500

In [47]:
# All values in the row have to have the same type for sorting by columns within row 2
df[["ID", "Posts", "Reputation"]].sort_values(by=2, axis=1, ascending=False)

   Reputation  Posts  ID
0         500  150.0   1
1         720  230.0   2
2         200   80.0   3
3         940  420.0   4
4         500    NaN   5

In [49]:
df?

Type:        DataFrame
String form:
ID Username  Age       Date  Posts  Reputation
           0   1   Victor   18 2032-01-01  150.0         5 <...>   4      Lev   38 2032-06-21  420.0         940
           4   5  Timofey   45 2032-09-15    NaN         500
Length:      5
File:        c:\python\python312\lib\site-packages\pandas\core\frame.py
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3