In [54]:
import pandas as pd
import numpy as np

users = {
    "ID": [1,2,3,4,5],
    "Username": ["Victor", "Alex", "Tanya", "Lev", "Timofey"],
    "Age": [18, 35, 25, 38, 45],
    "Date": pd.to_datetime(["2032-01-01", "2032-02-15","2032-04-25","2032-06-21","2032-09-15"]),
    "Posts": [150, 230, 80, 420, None],
    "Reputation": [500, 720, 200, 940, 500]
}
df = pd.DataFrame(users)
df

   ID Username  Age       Date  Posts  Reputation
0   1   Victor   18 2032-01-01  150.0         500
1   2     Alex   35 2032-02-15  230.0         720
2   3    Tanya   25 2032-04-25   80.0         200
3   4      Lev   38 2032-06-21  420.0         940
4   5  Timofey   45 2032-09-15    NaN         500

## Extend

In [55]:
df["Language"] = "English"
df

   ID Username  Age       Date  Posts  Reputation Language
0   1   Victor   18 2032-01-01  150.0         500  English
1   2     Alex   35 2032-02-15  230.0         720  English
2   3    Tanya   25 2032-04-25   80.0         200  English
3   4      Lev   38 2032-06-21  420.0         940  English
4   5  Timofey   45 2032-09-15    NaN         500  English

In [56]:
df["Active"] = [True, False, False, True, True]
df

   ID Username  Age       Date  Posts  Reputation Language  Active
0   1   Victor   18 2032-01-01  150.0         500  English    True
1   2     Alex   35 2032-02-15  230.0         720  English   False
2   3    Tanya   25 2032-04-25   80.0         200  English   False
3   4      Lev   38 2032-06-21  420.0         940  English    True
4   5  Timofey   45 2032-09-15    NaN         500  English    True

## Merge

In [57]:
comments = {
    "Comments": [70, 30, 45, 55, 80]
}
df2 = pd.DataFrame(comments)
df2

# Assign custom row indices
# df2 = pd.DataFrame(comments, index=["a", "b", "c", "d", "e"])

   Comments
0        70
1        30
2        45
3        55
4        80

In [58]:
df = pd.concat([df, df2], axis=1)
df

   ID Username  Age       Date  Posts  Reputation Language  Active  Comments
0   1   Victor   18 2032-01-01  150.0         500  English    True        70
1   2     Alex   35 2032-02-15  230.0         720  English   False        30
2   3    Tanya   25 2032-04-25   80.0         200  English   False        45
3   4      Lev   38 2032-06-21  420.0         940  English    True        55
4   5  Timofey   45 2032-09-15    NaN         500  English    True        80

## Drop

In [59]:
# Returns new dataframe, does not change the original dataframe
df.drop(["Language"], axis=1)

   ID Username  Age       Date  Posts  Reputation  Active  Comments
0   1   Victor   18 2032-01-01  150.0         500    True        70
1   2     Alex   35 2032-02-15  230.0         720   False        30
2   3    Tanya   25 2032-04-25   80.0         200   False        45
3   4      Lev   38 2032-06-21  420.0         940    True        55
4   5  Timofey   45 2032-09-15    NaN         500    True        80

In [60]:
# Change the original dataframe
if ("Language" in df.columns):
    df.drop(["Language"], axis=1, inplace=True)
df

   ID Username  Age       Date  Posts  Reputation  Active  Comments
0   1   Victor   18 2032-01-01  150.0         500    True        70
1   2     Alex   35 2032-02-15  230.0         720   False        30
2   3    Tanya   25 2032-04-25   80.0         200   False        45
3   4      Lev   38 2032-06-21  420.0         940    True        55
4   5  Timofey   45 2032-09-15    NaN         500    True        80

In [61]:
# Remove rows
df.drop([2, 3])

   ID Username  Age       Date  Posts  Reputation  Active  Comments
0   1   Victor   18 2032-01-01  150.0         500    True        70
1   2     Alex   35 2032-02-15  230.0         720   False        30
4   5  Timofey   45 2032-09-15    NaN         500    True        80